### PR TITLE
Update Ghidra to 9.0.4

### PR DESCRIPTION
**Pull request by jonasw234**

### CODE REVIEW

**Comment by jroimartin** [comment]
+1

It would be great to get this PR merged and update the package in chocolatey. It seems that the current one still depends on `jdk11` (currently broken) and the change to `openjdk11` has already been merged into master.

**Comment by jroimartin** [comment]
BTW it seems that the maintainer of `openjdk` in Chocolatey recommends to use [openjdk11](https://chocolatey.org/packages/openjdk11) for version 11:

http://disq.us/p/2090hy1

What about adding that change to this PR in order to get the ghidra package fully updated?

**Comment by jonasw234** [comment]
Agreed, good idea.  I’ve changed the dependency to use the openjdk11 package instead.  Thanks for letting me know!

**Comment by obilodeau** [comment]
Can this be merged and chocolatey updated please.

**Comment by AnthonyMastrean** [comment]
Thank you, all, for hanging on. Been dealing with some family medical health stuff... and I had *just* started looking into automatic packages. Gah!

**Comment by AnthonyMastrean** [comment]
Pushed, awaiting moderation!

https://chocolatey.org/packages/ghidra/9.0.4

**Comment by jonasw234** [comment]
Sorry to hear about your family!

I recently started using automatic packages as well, so if you need any help – though I am by no means an expert – you can check out my repo or hit me up.

**Pull request merged**
