### PR TITLE
Liquibase > Upgrade 3.6.1 -> 3.6.2

### PR DESCRIPTION
**Pull request by adriens**
Liquibase > Upgrade 3.6.1 -> 3.6.2, see  #305

### CODE REVIEW

**Comment by AnthonyMastrean** [comment]
😊🎄

**Comment by adriens** [comment]
Automate Liquibase nuspec and PS1 generation see #319

**Comment by adriens** [comment]
Hopefully you'll like it 😸 ❔

**Comment by adriens** [comment]
Wait until #320 is fixed 👍

**Comment by adriens** [comment]
It's all done, ready for merge. It does also fix the existing issue on SLF4J missing classes affectiin `3.6.0` and `3.6.1` versions.

Finally, the choco package will be easier to use than the native zip file 👍 👏

**Comment by adriens** [comment]
❓

**Comment by adriens** [comment]
Hi @AnthonyMastrean , what could be done to get this PR merged ?

**Comment by adriens** [comment]
@AnthonyMastrean : could you please tell me if you intend to merge this PR or if there is something wrong so the liquibase package can be updated to its latest version ?

**Comment by AnthonyMastrean** [comment]
Hey, sorry, having a baby! 😇 I’ll check in soon.

**Comment by adriens** [comment]
Enjoy @AnthonyMastrean  👶 ❤️ 🎆

**Comment by adriens** [comment]
Once this will have been merges, I'll implement the [3.6.3](https://github.com/liquibase/liquibase/releases/tag/liquibase-parent-3.6.3)

**Comment by adriens** [comment]
2019-02-17 10_56_22-chocolatey gallery _ liquibase 3 6 3

**Pull request closed without merging**
