### PR TITLE
Fix cloc and update to 1.80

### LINKED ISSUE #311: cloc broken
cloc package is broken. Looks like it is trying to download the exe from https://github.com/AlDanial/cloc/releases/download/v1.76/cloc-1.76.exe , but it should be https://github.com/AlDanial/cloc/releases/download/1.76/cloc-1.76.exe

Not sure why it worked before, but there is no "v" in the 1.76 tag on that repo.

Package Url: https://chocolatey.org/packages/CLOC

### PR DESCRIPTION
**Pull request by kspearrin**
resolves #311

### CODE REVIEW

**Comment by AnthonyMastrean** [comment]
Awesome, thanks! I was so excited that I merged without trying the branch first... we should update the version, too (I'll get it this time). https://github.com/AnthonyMastrean/chocolateypackages/blob/master/packages/cloc/cloc.nuspec#L6

**Comment by kspearrin** [comment]
Whoops. Thanks.

**Comment by gep13** [comment]
@AnthonyMastrean @kspearrin thank you both for getting this package updated!

**Comment by AnthonyMastrean** [comment]
@gep13 I'm going to try to convince the cloc author to take this over, but I might want to make it more automatic before then... what's the state of the art on automatic packages?

**Comment by gep13** [comment]
@AnthonyMastrean My suggestion would be to use AU.  It is being used on the Core Team Packages repository:

https://github.com/chocolatey/chocolatey-coreteampackages

And it has been working very well.

**Pull request merged**
