### PR TITLE
Updated the intellijidea-* packages to uninstall existing versions before installing the latest if an existing version exists

### PR DESCRIPTION
**Pull request by gigaSproule**
As the title states, this is to fix the problem where IntelliJ won't uninstall the older version first.

### CODE REVIEW

**Comment by AnthonyMastrean** [comment]
Thanks, @gigaSproule, but I don't really maintain this package anymore. @ZeddG93 and @jordigg are my usual merge requesters and I'll defer to their judgement here.

(While we're at it, zed/jordi, do you want to move this to your own repo yet?)

**Comment by ZeddG93** [comment]
I will try to use these codes in the next version, thanks.

Can I join the collaborators? @AnthonyMastrean

**Comment by ZeddG93** [comment]
I merged this code in PR #369 , but it didn't seem to work.

**Comment by gigaSproule** [comment]
That's weird, because I had repeatedly tested that locally. Also, when I upgraded my IntelliJ using the merged in version, it didn't uninstall the old one either...

**Comment by AnthonyMastrean** [comment]
Thank you! But, the maintainer of this package has changed... https://chocolatey.org/packages/intellijidea

**Pull request closed without merging**
