### PR TITLE
Update IntelliJ to v2016.3

### PR DESCRIPTION
**Pull request by jordigg**
Updated to v2016.3 and used the new uninstall method following Choco latest template

### CODE REVIEW

**Comment by MartyGentillon** [comment]
I presume that you have tested the install/uninstall loop?  (otherwise, this looks good)

**Comment by MartyGentillon** [comment]
It looks like there is a bug in the successful installation detection...

**Comment by MartyGentillon** [comment]
Or perhaps it is running the uninstaller twice...

**Comment by MartyGentillon** [comment]
So the problem seems to be that the auto uninstaller is running and failing to uninstall the package that the chocoUninstaller script just uninstalled.

**Comment by jordigg** [comment]
I've seen this issue before but though was part of the testing phase... When I uninstall it gets uninstalled successfully by the uninstall script and then attempts to do it via the autouninstaller, not sure why when the first uninstaller reported success...

**Comment by MartyGentillon** [comment]
Yep, that's exactly the behavior that I am seeing.  I am looking into it right now.

**Comment by MartyGentillon** [comment]
I have a guess, will let you know in a second.

**Comment by jordigg** [comment]
I can fix and push again if you figured out the problem. Maybe an wrong exit code on the uninstall script? Thought I used the templates choco provides :) thanks for your help!

**Comment by MartyGentillon** [comment]
That was my first guess, but I don't think so.  I am wondering if it is a race condition.

**Comment by MartyGentillon** [comment]
Definitely some kind of race condition.

**Comment by MartyGentillon** [comment]
I am looking into solutions now.

**Comment by MartyGentillon** [comment]
It seems that chocolatey 0.10.4 contains a fix.  

https://github.com/chocolatey/choco/issues/1035

For now, adding:

```
  # Temporary workaround for race condition in chocolaty 0.10.3.  The bug is fixed in 0.10.4.
  Start-Sleep -Seconds 10 
```
after line 31 seems to resolve the issue.

**Comment by jordigg** [comment]
that makes sense... Was also looking for known bugs. Will implement that to this package and submit again. Will also implement it on other package I contribute too until gets fixed on choco. Thanks again for your help!!

**Comment by MartyGentillon** [comment]
I will have a patch in a few moments

**Comment by MartyGentillon** [comment]
The updated request is:

https://github.com/AnthonyMastrean/chocolateypackages/pull/211

**Pull request merged**
