### PR TITLE
Update IntelliJIDEA to 2017.1

### PR DESCRIPTION
**Pull request by jordigg**

### CODE REVIEW

**Comment by MartyGentillon** [comment]
It doesn't look like you got the uninstall scripts, which mention a version number (IntelliJ IDEA 2016.3*)

**Comment by MartyGentillon** [comment]
Also, have you tested the install / uninstall loop?

**Comment by jordigg** [comment]
I did locally but forgot to push the latest commit with the uninstaller version corrected. Sorry about that!

**Comment by MartyGentillon** [comment]
Looks good to me.

**Pull request closed without merging**
