### PR TITLE
update gog before requesting exemption

### PR DESCRIPTION
**Pull request by AeliusSaionji**

### CODE REVIEW

**Comment by AeliusSaionji** [comment]
I've already sent the update and commented that it needs an exemption from the verifier.

**Comment by AnthonyMastrean** [comment]
I haven't had time to investigate... why does it need an exemption? Something can't run on that Windows Server 2012 R2 image?

**Comment by AeliusSaionji** [comment]
You added the required dependency, but it needs a reboot to finalize the install (for Windows 8 / Server 2012).

**Comment by AnthonyMastrean** [comment]
Wow, that shows how much I'm paying attention 😅 . I remember that was a moderation comment a _long time ago_. I guess there's no getting around the reboot?

**Comment by AeliusSaionji** [comment]
Not that I know of. Moderation should tell us if there is something we can try first

**Comment by dragon788** [comment]
If you can supply a link to an Appveyor run showing the successful install and installed state after reboot that can go a long ways towards proving it works (at least in my book).

**Pull request merged**
