### PR TITLE
intellijidea: update to 2018.2.6

### PR DESCRIPTION
**Pull request by ZeddG93**

### CODE REVIEW

**Comment by jordigg** [comment]
@ZeddG93 could I make you a maintainer of the community edition in order to upload both packages at the same time to the choco website?

**Comment by AnthonyMastrean** [comment]
I completely forgot that you two were different people. Thanks for asking, @jordigg! 😄

**Comment by AnthonyMastrean** [comment]
@ZeddG93 @jordigg do either of you have a package repo yet? I'd love to move this so one of you can manage it w/o me!

**Comment by AnthonyMastrean** [comment]
@ZeddG93 @jordigg even better would be making an "automatic" package and getting this submitted to the Chocolatey core team for maintenance... but I keep avoiding figuring out how to do that.

https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md

**Comment by ZeddG93** [comment]
> 
> 
> @ZeddG93 could I make you a maintainer of the community edition in order to upload both packages at the same time to the choco website?

yes u can

**Pull request merged**
