### PR TITLE
Package ag.exe version 2.2.5, from https://github.com/JFLarvoire

### PR DESCRIPTION
**Pull request by JFLarvoire**
Hi,
we exchanged emails last June about releasing an upgraded version of the ag package, based on my own improved builds for Windows.
I finally took time to prepare it this week-end, and here it is.

### CODE REVIEW

**Comment by AnthonyMastrean** [comment]
Do you have a Chocolatey user name? I'll add you as a maintainer and you can publish the new package.

**Comment by AnthonyMastrean** [comment]
Long term, I'll remove myself from the maintainer list, you could source control the Chocolatey package files directly in your application repository and use the choco command line to push new versions.

**Comment by JFLarvoire** [comment]
> Do you have a Chocolatey user name?

No, I don't have one.
I just searched on the chocolatey.org web site, but I can't find where I can create one. (Which is very strange: Too many web sites require you to create an account for no good reason, but it's the first time I see a web site that makes it hard to create one when one is needed!)

**Comment by AnthonyMastrean** [comment]
Oh my that link is very hidden! Here's what I found...
https://community.chocolatey.org/account/Register

**Comment by JFLarvoire** [comment]
Not quite there yet...  
I created an account using your link; Got the verification email from community.chocolatey.org; Clicked on the confirmation link in the email...  
And now I keep getting this error: (Reproduced on two different browsers)

> **Confirmation Error**
> <span style="color:red">Could not confirm your email address. Make sure you clicked on the confirmation URL in the email we sent.</span>
>
> If you see this screen and you are logged in, you can likely safely ignore it.

I tried clicking again on the link, but this does not help.
Any suggestion?

**Comment by JFLarvoire** [comment]
@AnthonyMastrean: Today I can login to chocolatey.org without any problem. No idea why it failed last time.
Anyway, my Chocolatey account is "jf.larvoire". If you can give me rights to the ag package, I'll appreciate.

**Comment by AnthonyMastrean** [comment]
Just added you!

**Pull request merged**
