### PR TITLE
Update IntelliJ to v2016.3

### PR DESCRIPTION
**Pull request by MartyGentillon**
Minor bug fix for https://github.com/AnthonyMastrean/chocolateypackages/pull/210

Passes install/uninstall loop as described in https://github.com/AnthonyMastrean/chocolateypackages/pull/204

### CODE REVIEW

**Comment by jordigg** [comment]
Could you also apply to community edition or should I? They have the same problem.

**Comment by MartyGentillon** [comment]
will do.

**Comment by jordigg** [comment]
Thanks so much! Will apply changes to the final package and submit to choco website.

**Comment by MartyGentillon** [comment]
done

**Pull request merged**
